name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2 
      with:
          # 是否docker push
          push: true
          tags: qiuyanlong/nest_blog_api:latest
          
    - name: Docker Hub Description
      # You may pin to the exact commit or the version.
      # uses: peter-evans/dockerhub-description@da890086d39c735e41d8823c8a95bde4302c3d64
      uses: peter-evans/dockerhub-description@v3.1.0
      with:
        # Docker Hub username
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        # Docker Hub password or Personal Access Token with read/write/delete scope
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        # Docker Hub repository in the format `<namespace>/<name>` Default: `github.repository`
        repository: qiuyanlong/nest_blog_api
        # Docker Hub repository short description
        short-description: nest docker-compose    


      
      
      
      
      
      
      
      
      
      
      
